# Generated by Django 3.0.2 on 2020-01-15 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTime', models.IntegerField()),
                ('restTime', models.IntegerField()),
                ('cycleNumber', models.IntegerField()),
                ('longRestTime', models.IntegerField()),
                ('status', model_utils.fields.StatusField(choices=[('using', 'using'), ('notUsing', 'notUsing')], default='using', max_length=100, no_check_for_status=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.Setlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
